// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/internal/v1/workflow/reset": {
            "post": {
                "description": "Deletes all scan sessions, file registry entries, and file metadata in a single transaction. Irreversible",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Workflow"
                ],
                "summary": "Reset all application data",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/db.ResetCounts"
                        }
                    }
                }
            }
        },
        "/internal/v1/workflow/scan": {
            "post": {
                "description": "Submit root paths to the pipeline. The API validates directories, removes overlapping child paths, returns the effective scanPaths, and then starts scanning immediately",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Workflow"
                ],
                "summary": "Start a new scan",
                "parameters": [
                    {
                        "description": "Scan Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/server.ScanRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/server.ScanResponse"
                        }
                    }
                }
            }
        },
        "/internal/v1/workflow/{id}/confirm": {
            "post": {
                "description": "Accepts the possibly edited tree, applies renames to target paths, marks entries APPROVED, and remembers renamed locations for future scans",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Workflow"
                ],
                "summary": "Confirm (approve/correct) the VFS directory tree",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Edited tree",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/server.ConfirmRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.ConfirmResponse"
                        }
                    }
                }
            }
        },
        "/internal/v1/workflow/{id}/tree": {
            "get": {
                "description": "Returns the proposed destination hierarchy (folder names only) for a session's files, for review before the move",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Workflow"
                ],
                "summary": "Get the proposed VFS directory tree",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.TreeResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "db.ResetCounts": {
            "type": "object",
            "properties": {
                "fileMetadataDeleted": {
                    "type": "integer"
                },
                "filesDeleted": {
                    "type": "integer"
                },
                "scanSessionsDeleted": {
                    "type": "integer"
                },
                "userLabelsDeleted": {
                    "type": "integer"
                },
                "vfsEntriesDeleted": {
                    "type": "integer"
                }
            }
        },
        "server.ConfirmRequest": {
            "type": "object",
            "required": [
                "tree"
            ],
            "properties": {
                "tree": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/vfs.Node"
                    }
                }
            }
        },
        "server.ConfirmResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "sessionId": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "server.ScanRequest": {
            "type": "object",
            "required": [
                "rootPaths"
            ],
            "properties": {
                "rootPaths": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "server.ScanResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "scanPaths": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "sessionId": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "server.TreeResponse": {
            "type": "object",
            "properties": {
                "sessionId": {
                    "type": "string"
                },
                "tree": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/vfs.Node"
                    }
                }
            }
        },
        "vfs.Node": {
            "type": "object",
            "properties": {
                "children": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/vfs.Node"
                    }
                },
                "fileCount": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "lat": {
                    "description": "Lat/Lon are one exemplar GPS coordinate for this node (only ever set on\nthe location-depth node, from the first GPS-tagged file that landed\nthere) — lets a review surface re-query the location resolver for ranked\nalternatives when the reviewer wants to correct a wrong name.",
                    "type": "number"
                },
                "lon": {
                    "type": "number"
                },
                "mergedIds": {
                    "description": "MergedIDs are the IDs of nodes a review-time merge folded into this one.\nThey no longer appear anywhere in the tree (the reviewer sees one folder,\nwhich is the whole point of merging), but their files still live under\nthose old paths in the DB, so Confirm must remap them here too.",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "name": {
                    "type": "string"
                },
                "samples": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "suggestions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/vfs.Suggestion"
                    }
                }
            }
        },
        "vfs.Suggestion": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "source": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "WanderSort API",
	Description:      "API documentation for WanderSort",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
