package classifier

type Jpeg struct {
	AEAverage                                          int      `json:"AEAverage"`
	AEBAutoCancel                                      int      `json:"AEBAutoCancel"`
	AEBBracketValue                                    int      `json:"AEBBracketValue"`
	AEBSequence                                        int      `json:"AEBSequence"`
	AEBShotCount                                       string   `json:"AEBShotCount"`
	AELockMeterModeAfterFocus                          int      `json:"AELockMeterModeAfterFocus"`
	AEStable                                           int      `json:"AEStable"`
	AETarget                                           int      `json:"AETarget"`
	AFAccelDecelTracking                               int      `json:"AFAccelDecelTracking"`
	AFAreaHeights                                      string   `json:"AFAreaHeights"`
	AFAreaMode                                         int      `json:"AFAreaMode"`
	AFAreaSelectionMethod                              int      `json:"AFAreaSelectionMethod"`
	AFAreaWidths                                       string   `json:"AFAreaWidths"`
	AFAreaXPositions                                   string   `json:"AFAreaXPositions"`
	AFAreaYPositions                                   string   `json:"AFAreaYPositions"`
	AFAssistBeam                                       int      `json:"AFAssistBeam"`
	AFConfidence                                       int      `json:"AFConfidence"`
	AFConfigTool                                       int      `json:"AFConfigTool"`
	AFImageHeight                                      int      `json:"AFImageHeight"`
	AFImageWidth                                       int      `json:"AFImageWidth"`
	AFMeasuredDepth                                    int      `json:"AFMeasuredDepth"`
	AFMicroAdjMode                                     int      `json:"AFMicroAdjMode"`
	AFMicroAdjValue                                    int      `json:"AFMicroAdjValue"`
	AFPerformance                                      string   `json:"AFPerformance"`
	AFPointDisplayDuringFocus                          int      `json:"AFPointDisplayDuringFocus"`
	AFPointSwitching                                   int      `json:"AFPointSwitching"`
	AFPointsInFocus                                    string   `json:"AFPointsInFocus"`
	AFPointsSelected                                   string   `json:"AFPointsSelected"`
	AFStable                                           int      `json:"AFStable"`
	AFStatusViewfinder                                 int      `json:"AFStatusViewfinder"`
	AFTrackingSensitivity                              int      `json:"AFTrackingSensitivity"`
	AIServoFirstImage                                  int      `json:"AIServoFirstImage"`
	AIServoSecondImage                                 int      `json:"AIServoSecondImage"`
	APP14Flags0                                        int      `json:"APP14Flags0"`
	APP14Flags1                                        int      `json:"APP14Flags1"`
	AToB0                                              string   `json:"AToB0"`
	AToB1                                              string   `json:"AToB1"`
	AToB2                                              string   `json:"AToB2"`
	AccelerationVector                                 string   `json:"AccelerationVector"`
	AddAspectRatioInfo                                 int      `json:"AddAspectRatioInfo"`
	AddIPTCInformation                                 int      `json:"AddIPTCInformation"`
	AlreadyApplied                                     bool     `json:"AlreadyApplied"`
	AmbienceSelection                                  int      `json:"AmbienceSelection"`
	AntiFlicker                                        int      `json:"AntiFlicker"`
	Aperture                                           float64  `json:"Aperture"`
	ApertureRange                                      string   `json:"ApertureRange"`
	ApertureValue                                      float64  `json:"ApertureValue"`
	ApplicationRecordVersion                           int      `json:"ApplicationRecordVersion"`
	ApproximateFocusDistance                           float64  `json:"ApproximateFocusDistance"`
	Artist                                             string   `json:"Artist"`
	AspectRatio                                        int      `json:"AspectRatio"`
	AudioCompression                                   int      `json:"AudioCompression"`
	AutoAFPointSelEOSiTRAF                             int      `json:"AutoAFPointSelEOSiTRAF"`
	AutoExposureBracketing                             int      `json:"AutoExposureBracketing"`
	AutoISO                                            int      `json:"AutoISO"`
	AutoLateralCA                                      int      `json:"AutoLateralCA"`
	AutoLightingOptimizer                              int      `json:"AutoLightingOptimizer"`
	AutoRotate                                         int      `json:"AutoRotate"`
	AutoWhiteVersion                                   int      `json:"AutoWhiteVersion"`
	BaseISO                                            int      `json:"BaseISO"`
	BatteryType                                        string   `json:"BatteryType"`
	BitsPerSample                                      int      `json:"BitsPerSample"`
	BlackMaskBottomBorder                              int      `json:"BlackMaskBottomBorder"`
	BlackMaskLeftBorder                                int      `json:"BlackMaskLeftBorder"`
	BlackMaskRightBorder                               int      `json:"BlackMaskRightBorder"`
	BlackMaskTopBorder                                 int      `json:"BlackMaskTopBorder"`
	Blacks2012                                         string   `json:"Blacks2012"`
	BlueBalance                                        float64  `json:"BlueBalance"`
	BlueHue                                            int      `json:"BlueHue"`
	BlueMatrixColumn                                   string   `json:"BlueMatrixColumn"`
	BlueSaturation                                     int      `json:"BlueSaturation"`
	BlueTRC                                            string   `json:"BlueTRC"`
	BracketMode                                        int      `json:"BracketMode"`
	BracketShotNumber                                  int      `json:"BracketShotNumber"`
	BracketValue                                       int      `json:"BracketValue"`
	BrightnessValue                                    float64  `json:"BrightnessValue"`
	BulbDuration                                       int      `json:"BulbDuration"`
	ByLine                                             string   `json:"By-line"`
	CFAPattern                                         string   `json:"CFAPattern"`
	CMMFlags                                           int      `json:"CMMFlags"`
	CameraProfile                                      string   `json:"CameraProfile"`
	CameraTemperature                                  int      `json:"CameraTemperature"`
	CameraType                                         int      `json:"CameraType"`
	CanonExposureMode                                  int      `json:"CanonExposureMode"`
	CanonFirmwareVersion                               string   `json:"CanonFirmwareVersion"`
	CanonFlashMode                                     int      `json:"CanonFlashMode"`
	CanonImageHeight                                   int      `json:"CanonImageHeight"`
	CanonImageSize                                     int      `json:"CanonImageSize"`
	CanonImageType                                     string   `json:"CanonImageType"`
	CanonImageWidth                                    int      `json:"CanonImageWidth"`
	CanonModelID                                       int64    `json:"CanonModelID"`
	CaptureMode                                        string   `json:"CaptureMode"`
	ChromaticAberrationCorr                            int      `json:"ChromaticAberrationCorr"`
	ChromaticAberrationSetting                         int      `json:"ChromaticAberrationSetting"`
	ChromaticAdaptation                                string   `json:"ChromaticAdaptation"`
	CircleOfConfusion                                  string   `json:"CircleOfConfusion"`
	Clarity                                            int      `json:"Clarity"`
	Clarity2012                                        string   `json:"Clarity2012"`
	CodedCharacterSet                                  string   `json:"CodedCharacterSet"`
	ColorComponents                                    int      `json:"ColorComponents"`
	ColorDataVersion                                   int      `json:"ColorDataVersion"`
	ColorNoiseReduction                                int      `json:"ColorNoiseReduction"`
	ColorNoiseReductionDetail                          int      `json:"ColorNoiseReductionDetail"`
	ColorNoiseReductionSmoothness                      int      `json:"ColorNoiseReductionSmoothness"`
	ColorSpace                                         int      `json:"ColorSpace"`
	ColorSpaceData                                     string   `json:"ColorSpaceData"`
	ColorTempAsShot                                    int      `json:"ColorTempAsShot"`
	ColorTempAuto                                      int      `json:"ColorTempAuto"`
	ColorTempCloudy                                    int      `json:"ColorTempCloudy"`
	ColorTempDaylight                                  int      `json:"ColorTempDaylight"`
	ColorTempFlash                                     int      `json:"ColorTempFlash"`
	ColorTempFluorescent                               int      `json:"ColorTempFluorescent"`
	ColorTempKelvin                                    int      `json:"ColorTempKelvin"`
	ColorTempMeasured                                  int      `json:"ColorTempMeasured"`
	ColorTempShade                                     int      `json:"ColorTempShade"`
	ColorTempTungsten                                  int      `json:"ColorTempTungsten"`
	ColorTemperature                                   int      `json:"ColorTemperature"`
	ColorTone                                          int      `json:"ColorTone"`
	ColorTransform                                     int      `json:"ColorTransform"`
	ComponentsConfiguration                            string   `json:"ComponentsConfiguration"`
	CompositeImage                                     int      `json:"CompositeImage"`
	Compression                                        int      `json:"Compression"`
	ConditionalFEC                                     int      `json:"ConditionalFEC"`
	ConnectionSpaceIlluminant                          string   `json:"ConnectionSpaceIlluminant"`
	ContentIdentifier                                  string   `json:"ContentIdentifier"`
	ContinuousDrive                                    int      `json:"ContinuousDrive"`
	Contrast                                           int      `json:"Contrast"`
	Contrast2012                                       int      `json:"Contrast2012"`
	ControlMode                                        int      `json:"ControlMode"`
	ControlRingRotation                                int      `json:"ControlRingRotation"`
	ConvertToGrayscale                                 bool     `json:"ConvertToGrayscale"`
	Copyright                                          string   `json:"Copyright"`
	CreateDate                                         string   `json:"CreateDate"`
	Creator                                            string   `json:"Creator"`
	CreatorTool                                        string   `json:"CreatorTool"`
	CropAngle                                          int      `json:"CropAngle"`
	CropBottom                                         float64  `json:"CropBottom"`
	CropBottomMargin                                   int      `json:"CropBottomMargin"`
	CropConstrainToWarp                                int      `json:"CropConstrainToWarp"`
	CropLeft                                           int      `json:"CropLeft"`
	CropLeftMargin                                     int      `json:"CropLeftMargin"`
	CropRight                                          int      `json:"CropRight"`
	CropRightMargin                                    int      `json:"CropRightMargin"`
	CropTop                                            float64  `json:"CropTop"`
	CropTopMargin                                      int      `json:"CropTopMargin"`
	CroppedAreaImageHeightPixels                       int      `json:"CroppedAreaImageHeightPixels"`
	CroppedAreaImageWidthPixels                        int      `json:"CroppedAreaImageWidthPixels"`
	CroppedAreaLeftPixels                              int      `json:"CroppedAreaLeftPixels"`
	CroppedAreaTopPixels                               int      `json:"CroppedAreaTopPixels"`
	CroppedImageHeight                                 int      `json:"CroppedImageHeight"`
	CroppedImageLeft                                   int      `json:"CroppedImageLeft"`
	CroppedImageTop                                    int      `json:"CroppedImageTop"`
	CroppedImageWidth                                  int      `json:"CroppedImageWidth"`
	CurrentIPTCDigest                                  string   `json:"CurrentIPTCDigest"`
	CustomControls                                     string   `json:"CustomControls"`
	CustomPictureStyleFileName                         string   `json:"CustomPictureStyleFileName"`
	CustomRendered                                     int      `json:"CustomRendered"`
	DCTEncodeVersion                                   int      `json:"DCTEncodeVersion"`
	Dof                                                string   `json:"DOF"`
	DateCreated                                        string   `json:"DateCreated"`
	DateTimeCreated                                    string   `json:"DateTimeCreated"`
	DateTimeOriginal                                   string   `json:"DateTimeOriginal"`
	DaylightSavings                                    int      `json:"DaylightSavings"`
	DefaultEraseOption                                 int      `json:"DefaultEraseOption"`
	DefringeGreenAmount                                int      `json:"DefringeGreenAmount"`
	DefringeGreenHueHi                                 int      `json:"DefringeGreenHueHi"`
	DefringeGreenHueLo                                 int      `json:"DefringeGreenHueLo"`
	DefringePurpleAmount                               int      `json:"DefringePurpleAmount"`
	DefringePurpleHueHi                                int      `json:"DefringePurpleHueHi"`
	DefringePurpleHueLo                                int      `json:"DefringePurpleHueLo"`
	Dehaze                                             int      `json:"Dehaze"`
	DependentImage1EntryNumber                         int      `json:"DependentImage1EntryNumber"`
	DependentImage2EntryNumber                         int      `json:"DependentImage2EntryNumber"`
	DerivedFrom                                        string   `json:"DerivedFrom"`
	DerivedFromDocumentID                              string   `json:"DerivedFromDocumentID"`
	DerivedFromInstanceID                              string   `json:"DerivedFromInstanceID"`
	DerivedFromOriginalDocumentID                      string   `json:"DerivedFromOriginalDocumentID"`
	DeviceAttributes                                   string   `json:"DeviceAttributes"`
	DeviceManufacturer                                 string   `json:"DeviceManufacturer"`
	DeviceMfgDesc                                      string   `json:"DeviceMfgDesc"`
	DeviceModel                                        string   `json:"DeviceModel"`
	DeviceModelDesc                                    string   `json:"DeviceModelDesc"`
	DialDirectionTvAv                                  int      `json:"DialDirectionTvAv"`
	DigitalCreationDate                                string   `json:"DigitalCreationDate"`
	DigitalCreationDateTime                            string   `json:"DigitalCreationDateTime"`
	DigitalCreationTime                                string   `json:"DigitalCreationTime"`
	DigitalGain                                        int      `json:"DigitalGain"`
	DigitalLensOptimizer                               int      `json:"DigitalLensOptimizer"`
	DigitalLensOptimizerSetting                        int      `json:"DigitalLensOptimizerSetting"`
	DigitalZoom                                        int      `json:"DigitalZoom"`
	DigitalZoomRatio                                   int      `json:"DigitalZoomRatio"`
	Directory                                          string   `json:"Directory"`
	DisplayedUnitsX                                    int      `json:"DisplayedUnitsX"`
	DisplayedUnitsY                                    int      `json:"DisplayedUnitsY"`
	DistortionCorrection                               int      `json:"DistortionCorrection"`
	DistortionCorrectionAlreadyApplied                 bool     `json:"DistortionCorrectionAlreadyApplied"`
	DistortionCorrectionSetting                        int      `json:"DistortionCorrectionSetting"`
	DistortionCorrectionValue                          int      `json:"DistortionCorrectionValue"`
	DocumentID                                         string   `json:"DocumentID"`
	DriveMode                                          int      `json:"DriveMode"`
	DualPixelRaw                                       int      `json:"DualPixelRaw"`
	DustRemovalData                                    string   `json:"DustRemovalData"`
	EasyMode                                           int      `json:"EasyMode"`
	EncodingProcess                                    int      `json:"EncodingProcess"`
	EnvelopeRecordVersion                              int      `json:"EnvelopeRecordVersion"`
	ExifByteOrder                                      string   `json:"ExifByteOrder"`
	ExifImageHeight                                    int      `json:"ExifImageHeight"`
	ExifImageWidth                                     int      `json:"ExifImageWidth"`
	ExifToolVersion                                    float64  `json:"ExifToolVersion"`
	ExifVersion                                        string   `json:"ExifVersion"`
	Exposure2012                                       float64  `json:"Exposure2012"`
	ExposureCompensation                               int      `json:"ExposureCompensation"`
	ExposureLevelIncrements                            int      `json:"ExposureLevelIncrements"`
	ExposureMode                                       int      `json:"ExposureMode"`
	ExposureProgram                                    int      `json:"ExposureProgram"`
	ExposureTime                                       float64  `json:"ExposureTime"`
	EyeDetection                                       int      `json:"EyeDetection"`
	FNumber                                            float64  `json:"FNumber"`
	Fov                                                float64  `json:"FOV"`
	FileAccessDate                                     string   `json:"FileAccessDate"`
	FileInodeChangeDate                                string   `json:"FileInodeChangeDate"`
	FileModifyDate                                     string   `json:"FileModifyDate"`
	FileName                                           string   `json:"FileName"`
	FilePermissions                                    int      `json:"FilePermissions"`
	FileSize                                           int      `json:"FileSize"`
	FileSource                                         int      `json:"FileSource"`
	FileType                                           string   `json:"FileType"`
	FileTypeExtension                                  string   `json:"FileTypeExtension"`
	Firmware                                           string   `json:"Firmware"`
	FisheyeFilter                                      int      `json:"FisheyeFilter"`
	Flash                                              int      `json:"Flash"`
	FlashBatteryLevel                                  int      `json:"FlashBatteryLevel"`
	FlashBits                                          int      `json:"FlashBits"`
	FlashCompensation                                  int      `json:"FlashCompensation"`
	FlashExposureComp                                  int      `json:"FlashExposureComp"`
	FlashExposureLock                                  int      `json:"FlashExposureLock"`
	FlashGuideNumber                                   int      `json:"FlashGuideNumber"`
	FlashModel                                         int      `json:"FlashModel"`
	FlashOutput                                        string   `json:"FlashOutput"`
	FlashType                                          int      `json:"FlashType"`
	FlashpixVersion                                    string   `json:"FlashpixVersion"`
	FocalLength                                        float64  `json:"FocalLength"`
	FocalLength35Efl                                   int      `json:"FocalLength35efl"`
	FocalLengthIn35MmFormat                            int      `json:"FocalLengthIn35mmFormat"`
	FocalPlaneResolutionUnit                           int      `json:"FocalPlaneResolutionUnit"`
	FocalPlaneXResolution                              float64  `json:"FocalPlaneXResolution"`
	FocalPlaneYResolution                              float64  `json:"FocalPlaneYResolution"`
	FocalType                                          int      `json:"FocalType"`
	FocalUnits                                         int      `json:"FocalUnits"`
	FocusBracketing                                    int      `json:"FocusBracketing"`
	FocusBracketingCropDepthComposite                  int      `json:"FocusBracketingCropDepthComposite"`
	FocusBracketingDepthComposite                      int      `json:"FocusBracketingDepthComposite"`
	FocusBracketingExposureSmoothing                   int      `json:"FocusBracketingExposureSmoothing"`
	FocusBracketingFlashInterval                       int      `json:"FocusBracketingFlashInterval"`
	FocusBracketingFocusIncrement                      int      `json:"FocusBracketingFocusIncrement"`
	FocusBracketingImageCount                          int      `json:"FocusBracketingImageCount"`
	FocusContinuous                                    int      `json:"FocusContinuous"`
	FocusDistanceLower                                 float64  `json:"FocusDistanceLower"`
	FocusDistanceRange                                 string   `json:"FocusDistanceRange"`
	FocusDistanceUpper                                 float64  `json:"FocusDistanceUpper"`
	FocusMode                                          int      `json:"FocusMode"`
	FocusPosition                                      int      `json:"FocusPosition"`
	FocusRange                                         int      `json:"FocusRange"`
	Format                                             string   `json:"Format"`
	FullPanoHeightPixels                               int      `json:"FullPanoHeightPixels"`
	FullPanoWidthPixels                                int      `json:"FullPanoWidthPixels"`
	GPSAltitude                                        float64  `json:"GPSAltitude"`
	GPSAltitudeRef                                     int      `json:"GPSAltitudeRef"`
	GPSDateStamp                                       string   `json:"GPSDateStamp"`
	GPSDateTime                                        string   `json:"GPSDateTime"`
	GPSLatitude                                        float64  `json:"GPSLatitude"`
	GPSLatitudeRef                                     string   `json:"GPSLatitudeRef"`
	GPSLongitude                                       float64  `json:"GPSLongitude"`
	GPSLongitudeRef                                    string   `json:"GPSLongitudeRef"`
	GPSPosition                                        string   `json:"GPSPosition"`
	GPSTimeStamp                                       string   `json:"GPSTimeStamp"`
	GPSVersionID                                       string   `json:"GPSVersionID"`
	GainControl                                        int      `json:"GainControl"`
	GrainAmount                                        int      `json:"GrainAmount"`
	GrainyBWFilter                                     int      `json:"GrainyBWFilter"`
	GreenHue                                           int      `json:"GreenHue"`
	GreenMatrixColumn                                  string   `json:"GreenMatrixColumn"`
	GreenSaturation                                    int      `json:"GreenSaturation"`
	GreenTRC                                           string   `json:"GreenTRC"`
	Hdr                                                int      `json:"HDR"`
	HDRPQ                                              int      `json:"HDR-PQ"`
	HDREffect                                          int      `json:"HDREffect"`
	HDRGain                                            float64  `json:"HDRGain"`
	HDRHeadroom                                        float64  `json:"HDRHeadroom"`
	HasCrop                                            bool     `json:"HasCrop"`
	HasSettings                                        bool     `json:"HasSettings"`
	HighISONoiseReduction                              int      `json:"HighISONoiseReduction"`
	HighlightTonePriority                              int      `json:"HighlightTonePriority"`
	Highlights2012                                     string   `json:"Highlights2012"`
	HistoryAction                                      []string `json:"HistoryAction"`
	HistoryChanged                                     string   `json:"HistoryChanged"`
	HistoryInstanceID                                  string   `json:"HistoryInstanceID"`
	HistoryParameters                                  string   `json:"HistoryParameters"`
	HistorySoftwareAgent                               string   `json:"HistorySoftwareAgent"`
	HistoryWhen                                        string   `json:"HistoryWhen"`
	HostComputer                                       string   `json:"HostComputer"`
	HueAdjustmentAqua                                  int      `json:"HueAdjustmentAqua"`
	HueAdjustmentBlue                                  int      `json:"HueAdjustmentBlue"`
	HueAdjustmentGreen                                 int      `json:"HueAdjustmentGreen"`
	HueAdjustmentMagenta                               int      `json:"HueAdjustmentMagenta"`
	HueAdjustmentOrange                                int      `json:"HueAdjustmentOrange"`
	HueAdjustmentPurple                                int      `json:"HueAdjustmentPurple"`
	HueAdjustmentRed                                   int      `json:"HueAdjustmentRed"`
	HueAdjustmentYellow                                int      `json:"HueAdjustmentYellow"`
	HyperfocalDistance                                 float64  `json:"HyperfocalDistance"`
	IPTCDigest                                         string   `json:"IPTCDigest"`
	Iso                                                int      `json:"ISO"`
	ISOSpeedIncrements                                 int      `json:"ISOSpeedIncrements"`
	ImageCaptureType                                   int      `json:"ImageCaptureType"`
	ImageHeight                                        int      `json:"ImageHeight"`
	ImageNumber                                        int      `json:"ImageNumber"`
	ImageSize                                          string   `json:"ImageSize"`
	ImageStabilization                                 int      `json:"ImageStabilization"`
	ImageUniqueID                                      string   `json:"ImageUniqueID"`
	ImageWidth                                         int      `json:"ImageWidth"`
	IncrementalTemperature                             int      `json:"IncrementalTemperature"`
	IncrementalTint                                    int      `json:"IncrementalTint"`
	InitialAFPointInServo                              int      `json:"InitialAFPointInServo"`
	InitialHorizontalFOVDegrees                        int      `json:"InitialHorizontalFOVDegrees"`
	InitialViewVerticalFOVDegrees                      int      `json:"InitialViewVerticalFOVDegrees"`
	InstanceID                                         string   `json:"InstanceID"`
	InternalSerialNumber                               string   `json:"InternalSerialNumber"`
	InteropIndex                                       string   `json:"InteropIndex"`
	InteropVersion                                     string   `json:"InteropVersion"`
	IsHDRActive                                        bool     `json:"IsHDRActive"`
	IsMergedPanorama                                   bool     `json:"IsMergedPanorama"`
	JFIFVersion                                        string   `json:"JFIFVersion"`
	LateralChromaticAberrationCorrectionAlreadyApplied bool     `json:"LateralChromaticAberrationCorrectionAlreadyApplied"`
	Lens                                               int      `json:"Lens"`
	Lens35Efl                                          float64  `json:"Lens35efl"`
	LensDriveWhenAFImpossible                          int      `json:"LensDriveWhenAFImpossible"`
	LensFacing                                         string   `json:"LensFacing"`
	LensID                                             string   `json:"LensID"`
	LensInfo                                           string   `json:"LensInfo"`
	LensMake                                           string   `json:"LensMake"`
	LensManualDistortionAmount                         int      `json:"LensManualDistortionAmount"`
	LensModel                                          string   `json:"LensModel"`
	LensProfileChromaticAberrationScale                int      `json:"LensProfileChromaticAberrationScale"`
	LensProfileDigest                                  string   `json:"LensProfileDigest"`
	LensProfileDistortionScale                         int      `json:"LensProfileDistortionScale"`
	LensProfileEnable                                  int      `json:"LensProfileEnable"`
	LensProfileFilename                                string   `json:"LensProfileFilename"`
	LensProfileName                                    string   `json:"LensProfileName"`
	LensProfileSetup                                   string   `json:"LensProfileSetup"`
	LensProfileVignettingScale                         int      `json:"LensProfileVignettingScale"`
	LensSerialNumber                                   int64    `json:"LensSerialNumber"`
	LensType                                           int      `json:"LensType"`
	LightSource                                        int      `json:"LightSource"`
	LightValue                                         float64  `json:"LightValue"`
	LinearityUpperMargin                               int      `json:"LinearityUpperMargin"`
	LivePhotoVideoIndex                                int      `json:"LivePhotoVideoIndex"`
	LiveViewShooting                                   int      `json:"LiveViewShooting"`
	LongExposureNoiseReduction                         int      `json:"LongExposureNoiseReduction"`
	Luminance                                          string   `json:"Luminance"`
	LuminanceAdjustmentAqua                            int      `json:"LuminanceAdjustmentAqua"`
	LuminanceAdjustmentBlue                            int      `json:"LuminanceAdjustmentBlue"`
	LuminanceAdjustmentGreen                           int      `json:"LuminanceAdjustmentGreen"`
	LuminanceAdjustmentMagenta                         int      `json:"LuminanceAdjustmentMagenta"`
	LuminanceAdjustmentOrange                          int      `json:"LuminanceAdjustmentOrange"`
	LuminanceAdjustmentPurple                          int      `json:"LuminanceAdjustmentPurple"`
	LuminanceAdjustmentRed                             int      `json:"LuminanceAdjustmentRed"`
	LuminanceAdjustmentYellow                          int      `json:"LuminanceAdjustmentYellow"`
	LuminanceNoiseAmplitude                            float64  `json:"LuminanceNoiseAmplitude"`
	LuminanceNoiseReductionContrast                    int      `json:"LuminanceNoiseReductionContrast"`
	LuminanceNoiseReductionDetail                      int      `json:"LuminanceNoiseReductionDetail"`
	LuminanceSmoothing                                 int      `json:"LuminanceSmoothing"`
	MIMEType                                           string   `json:"MIMEType"`
	MPFVersion                                         string   `json:"MPFVersion"`
	MPImage2                                           string   `json:"MPImage2"`
	MPImageFlags                                       int      `json:"MPImageFlags"`
	MPImageFormat                                      int      `json:"MPImageFormat"`
	MPImageLength                                      int      `json:"MPImageLength"`
	MPImageStart                                       int      `json:"MPImageStart"`
	MPImageType                                        int      `json:"MPImageType"`
	MacroMode                                          int      `json:"MacroMode"`
	Make                                               string   `json:"Make"`
	MakerNoteVersion                                   int      `json:"MakerNoteVersion"`
	ManualAFPointSelPattern                            int      `json:"ManualAFPointSelPattern"`
	ManualFlashOutput                                  int      `json:"ManualFlashOutput"`
	MaxAperture                                        float64  `json:"MaxAperture"`
	MaxApertureValue                                   float64  `json:"MaxApertureValue"`
	MaxFocalLength                                     int      `json:"MaxFocalLength"`
	MeasuredEV                                         float64  `json:"MeasuredEV"`
	MeasuredEV2                                        int      `json:"MeasuredEV2"`
	MeasuredRGGB                                       string   `json:"MeasuredRGGB"`
	MeasurementBacking                                 string   `json:"MeasurementBacking"`
	MeasurementFlare                                   float64  `json:"MeasurementFlare"`
	MeasurementGeometry                                int      `json:"MeasurementGeometry"`
	MeasurementIlluminant                              int      `json:"MeasurementIlluminant"`
	MeasurementObserver                                int      `json:"MeasurementObserver"`
	MediaBlackPoint                                    string   `json:"MediaBlackPoint"`
	MediaWhitePoint                                    string   `json:"MediaWhitePoint"`
	Megapixels                                         float64  `json:"Megapixels"`
	MetadataDate                                       string   `json:"MetadataDate"`
	MeteringMode                                       int      `json:"MeteringMode"`
	MinAperture                                        float64  `json:"MinAperture"`
	MinFocalLength                                     int      `json:"MinFocalLength"`
	MiniatureFilter                                    int      `json:"MiniatureFilter"`
	MiniatureFilterOrientation                         int      `json:"MiniatureFilterOrientation"`
	MiniatureFilterParameter                           int      `json:"MiniatureFilterParameter"`
	MiniatureFilterPosition                            int      `json:"MiniatureFilterPosition"`
	Model                                              string   `json:"Model"`
	ModifyDate                                         string   `json:"ModifyDate"`
	MultiExposure                                      int      `json:"MultiExposure"`
	MultiExposureControl                               int      `json:"MultiExposureControl"`
	MultiExposureShots                                 int      `json:"MultiExposureShots"`
	NDFilter                                           int      `json:"NDFilter"`
	NormalWhiteLevel                                   int      `json:"NormalWhiteLevel"`
	NumAFPoints                                        int      `json:"NumAFPoints"`
	NumberOfImages                                     int      `json:"NumberOfImages"`
	OISMode                                            int      `json:"OISMode"`
	OffsetTime                                         string   `json:"OffsetTime"`
	OffsetTimeDigitized                                string   `json:"OffsetTimeDigitized"`
	OffsetTimeOriginal                                 string   `json:"OffsetTimeOriginal"`
	OneShotAFRelease                                   int      `json:"OneShotAFRelease"`
	OpticalZoomCode                                    int      `json:"OpticalZoomCode"`
	Orientation                                        int      `json:"Orientation"`
	OrientationLinkedAF                                int      `json:"OrientationLinkedAF"`
	OriginalDocumentID                                 string   `json:"OriginalDocumentID"`
	OriginalImageHeight                                int      `json:"OriginalImageHeight"`
	OriginalImageWidth                                 int      `json:"OriginalImageWidth"`
	OwnerName                                          string   `json:"OwnerName"`
	PaintingFilter                                     int      `json:"PaintingFilter"`
	ParametricDarks                                    int      `json:"ParametricDarks"`
	ParametricHighlightSplit                           int      `json:"ParametricHighlightSplit"`
	ParametricHighlights                               int      `json:"ParametricHighlights"`
	ParametricLights                                   int      `json:"ParametricLights"`
	ParametricMidtoneSplit                             int      `json:"ParametricMidtoneSplit"`
	ParametricShadowSplit                              int      `json:"ParametricShadowSplit"`
	ParametricShadows                                  int      `json:"ParametricShadows"`
	PerChannelBlackLevel                               string   `json:"PerChannelBlackLevel"`
	PeripheralIlluminationCorr                         int      `json:"PeripheralIlluminationCorr"`
	PeripheralLighting                                 int      `json:"PeripheralLighting"`
	PeripheralLightingSetting                          int      `json:"PeripheralLightingSetting"`
	PeripheralLightingValue                            int      `json:"PeripheralLightingValue"`
	PerspectiveAspect                                  int      `json:"PerspectiveAspect"`
	PerspectiveHorizontal                              int      `json:"PerspectiveHorizontal"`
	PerspectiveRotate                                  int      `json:"PerspectiveRotate"`
	PerspectiveScale                                   int      `json:"PerspectiveScale"`
	PerspectiveUpright                                 int      `json:"PerspectiveUpright"`
	PerspectiveVertical                                int      `json:"PerspectiveVertical"`
	PerspectiveX                                       int      `json:"PerspectiveX"`
	PerspectiveY                                       int      `json:"PerspectiveY"`
	PhotoIdentifier                                    string   `json:"PhotoIdentifier"`
	PhotosAppFeatureFlags                              int      `json:"PhotosAppFeatureFlags"`
	PhotoshopThumbnail                                 string   `json:"PhotoshopThumbnail"`
	PictureStyle                                       int      `json:"PictureStyle"`
	PictureStylePC                                     string   `json:"PictureStylePC"`
	PictureStyleUserDef                                string   `json:"PictureStyleUserDef"`
	PoseHeadingDegrees                                 int      `json:"PoseHeadingDegrees"`
	PosePitchDegrees                                   int      `json:"PosePitchDegrees"`
	PoseRollDegrees                                    int      `json:"PoseRollDegrees"`
	PostCropVignetteAmount                             int      `json:"PostCropVignetteAmount"`
	PostCropVignetteFeather                            int      `json:"PostCropVignetteFeather"`
	PostCropVignetteHighlightContrast                  int      `json:"PostCropVignetteHighlightContrast"`
	PostCropVignetteMidpoint                           int      `json:"PostCropVignetteMidpoint"`
	PostCropVignetteRoundness                          int      `json:"PostCropVignetteRoundness"`
	PostCropVignetteStyle                              int      `json:"PostCropVignetteStyle"`
	PreviewImage                                       string   `json:"PreviewImage"`
	PrimaryPlatform                                    string   `json:"PrimaryPlatform"`
	ProcessVersion                                     float64  `json:"ProcessVersion"`
	ProfileCMMType                                     string   `json:"ProfileCMMType"`
	ProfileClass                                       string   `json:"ProfileClass"`
	ProfileConnectionSpace                             string   `json:"ProfileConnectionSpace"`
	ProfileCopyright                                   string   `json:"ProfileCopyright"`
	ProfileCreator                                     string   `json:"ProfileCreator"`
	ProfileDateTime                                    string   `json:"ProfileDateTime"`
	ProfileDescription                                 string   `json:"ProfileDescription"`
	ProfileFileSignature                               string   `json:"ProfileFileSignature"`
	ProfileID                                          string   `json:"ProfileID"`
	ProfileVersion                                     int      `json:"ProfileVersion"`
	ProjectionType                                     string   `json:"ProjectionType"`
	Quality                                            int      `json:"Quality"`
	RFLensType                                         int      `json:"RFLensType"`
	Rating                                             int      `json:"Rating"`
	RawFileName                                        string   `json:"RawFileName"`
	RawJpgSize                                         int      `json:"RawJpgSize"`
	RecommendedExposureIndex                           int      `json:"RecommendedExposureIndex"`
	RecordMode                                         int      `json:"RecordMode"`
	RedBalance                                         float64  `json:"RedBalance"`
	RedEyeReduction                                    int      `json:"RedEyeReduction"`
	RedHue                                             int      `json:"RedHue"`
	RedMatrixColumn                                    string   `json:"RedMatrixColumn"`
	RedSaturation                                      int      `json:"RedSaturation"`
	RedTRC                                             string   `json:"RedTRC"`
	RegionAppliedToDimensionsH                         int      `json:"RegionAppliedToDimensionsH"`
	RegionAppliedToDimensionsUnit                      string   `json:"RegionAppliedToDimensionsUnit"`
	RegionAppliedToDimensionsW                         int      `json:"RegionAppliedToDimensionsW"`
	RegionAreaH                                        []string `json:"RegionAreaH"`
	RegionAreaUnit                                     []string `json:"RegionAreaUnit"`
	RegionAreaW                                        []string `json:"RegionAreaW"`
	RegionAreaX                                        []any    `json:"RegionAreaX"`
	RegionAreaY                                        []string `json:"RegionAreaY"`
	RegionExtensions                                   string   `json:"RegionExtensions"`
	RegionExtensionsAngleInfoRoll                      int      `json:"RegionExtensionsAngleInfoRoll"`
	RegionExtensionsAngleInfoYaw                       int      `json:"RegionExtensionsAngleInfoYaw"`
	RegionExtensionsConfidenceLevel                    int      `json:"RegionExtensionsConfidenceLevel"`
	RegionExtensionsFaceID                             int      `json:"RegionExtensionsFaceID"`
	RegionType                                         []string `json:"RegionType"`
	RenderingIntent                                    int      `json:"RenderingIntent"`
	ResolutionUnit                                     int      `json:"ResolutionUnit"`
	RetouchAreaFeather                                 int      `json:"RetouchAreaFeather"`
	RetouchAreaHealVersion                             string   `json:"RetouchAreaHealVersion"`
	RetouchAreaMaskAlpha                               int      `json:"RetouchAreaMaskAlpha"`
	RetouchAreaMaskCenterValue                         int      `json:"RetouchAreaMaskCenterValue"`
	RetouchAreaMaskCenterWeight                        float64  `json:"RetouchAreaMaskCenterWeight"`
	RetouchAreaMaskDabs                                string   `json:"RetouchAreaMaskDabs"`
	RetouchAreaMaskFlow                                int      `json:"RetouchAreaMaskFlow"`
	RetouchAreaMaskPerimeterValue                      int      `json:"RetouchAreaMaskPerimeterValue"`
	RetouchAreaMaskRadius                              float64  `json:"RetouchAreaMaskRadius"`
	RetouchAreaMaskSizeX                               float64  `json:"RetouchAreaMaskSizeX"`
	RetouchAreaMaskSizeY                               float64  `json:"RetouchAreaMaskSizeY"`
	RetouchAreaMaskValue                               int      `json:"RetouchAreaMaskValue"`
	RetouchAreaMaskWhat                                string   `json:"RetouchAreaMaskWhat"`
	RetouchAreaMaskX                                   float64  `json:"RetouchAreaMaskX"`
	RetouchAreaMaskY                                   float64  `json:"RetouchAreaMaskY"`
	RetouchAreaMethod                                  string   `json:"RetouchAreaMethod"`
	RetouchAreaOffsetY                                 float64  `json:"RetouchAreaOffsetY"`
	RetouchAreaOpacity                                 int      `json:"RetouchAreaOpacity"`
	RetouchAreaSeed                                    string   `json:"RetouchAreaSeed"`
	RetouchAreaSourceState                             string   `json:"RetouchAreaSourceState"`
	RetouchAreaSourceX                                 float64  `json:"RetouchAreaSourceX"`
	RetouchAreaSpotType                                string   `json:"RetouchAreaSpotType"`
	RetouchInfo                                        []string `json:"RetouchInfo"`
	RetractLensOnPowerOff                              int      `json:"RetractLensOnPowerOff"`
	RunTimeEpoch                                       int      `json:"RunTimeEpoch"`
	RunTimeFlags                                       int      `json:"RunTimeFlags"`
	RunTimeScale                                       int      `json:"RunTimeScale"`
	RunTimeSincePowerUp                                float64  `json:"RunTimeSincePowerUp"`
	RunTimeValue                                       int64    `json:"RunTimeValue"`
	SafetyShift                                        int      `json:"SafetyShift"`
	SameExposureForNewAperture                         int      `json:"SameExposureForNewAperture"`
	Saturation                                         int      `json:"Saturation"`
	SaturationAdjustmentAqua                           int      `json:"SaturationAdjustmentAqua"`
	SaturationAdjustmentBlue                           string   `json:"SaturationAdjustmentBlue"`
	SaturationAdjustmentGreen                          int      `json:"SaturationAdjustmentGreen"`
	SaturationAdjustmentMagenta                        int      `json:"SaturationAdjustmentMagenta"`
	SaturationAdjustmentOrange                         string   `json:"SaturationAdjustmentOrange"`
	SaturationAdjustmentPurple                         string   `json:"SaturationAdjustmentPurple"`
	SaturationAdjustmentRed                            int      `json:"SaturationAdjustmentRed"`
	SaturationAdjustmentYellow                         string   `json:"SaturationAdjustmentYellow"`
	ScaleFactor35Efl                                   float64  `json:"ScaleFactor35efl"`
	Scene                                              string   `json:"Scene"`
	SceneCaptureType                                   int      `json:"SceneCaptureType"`
	SceneType                                          int      `json:"SceneType"`
	SelectAFAreaSelectionMode                          int      `json:"SelectAFAreaSelectionMode"`
	SelfTimer                                          int      `json:"SelfTimer"`
	SensingMethod                                      int      `json:"SensingMethod"`
	SensitivityType                                    int      `json:"SensitivityType"`
	SensorBlueLevel                                    int      `json:"SensorBlueLevel"`
	SensorBottomBorder                                 int      `json:"SensorBottomBorder"`
	SensorHeight                                       int      `json:"SensorHeight"`
	SensorLeftBorder                                   int      `json:"SensorLeftBorder"`
	SensorRedLevel                                     int      `json:"SensorRedLevel"`
	SensorRightBorder                                  int      `json:"SensorRightBorder"`
	SensorTopBorder                                    int      `json:"SensorTopBorder"`
	SensorWidth                                        int      `json:"SensorWidth"`
	SequenceNumber                                     int      `json:"SequenceNumber"`
	SerialNumber                                       int64    `json:"SerialNumber"`
	ShadowTint                                         int      `json:"ShadowTint"`
	Shadows2012                                        string   `json:"Shadows2012"`
	SharpenDetail                                      int      `json:"SharpenDetail"`
	SharpenEdgeMasking                                 int      `json:"SharpenEdgeMasking"`
	SharpenRadius                                      string   `json:"SharpenRadius"`
	Sharpness                                          int      `json:"Sharpness"`
	SharpnessFrequency                                 int      `json:"SharpnessFrequency"`
	ShootingMode                                       int      `json:"ShootingMode"`
	ShutterCount                                       int      `json:"ShutterCount"`
	ShutterCurtainHack                                 int      `json:"ShutterCurtainHack"`
	ShutterMode                                        int      `json:"ShutterMode"`
	ShutterReleaseWithoutLens                          int      `json:"ShutterReleaseWithoutLens"`
	ShutterSpeed                                       float64  `json:"ShutterSpeed"`
	ShutterSpeedRange                                  string   `json:"ShutterSpeedRange"`
	ShutterSpeedValue                                  string   `json:"ShutterSpeedValue"`
	SignalToNoiseRatio                                 float64  `json:"SignalToNoiseRatio"`
	SlowShutter                                        int      `json:"SlowShutter"`
	SoftFocusFilter                                    int      `json:"SoftFocusFilter"`
	Software                                           float64  `json:"Software"`
	SourceFile                                         string   `json:"SourceFile"`
	SpecularWhiteLevel                                 int      `json:"SpecularWhiteLevel"`
	SplitToningBalance                                 int      `json:"SplitToningBalance"`
	SplitToningHighlightHue                            int      `json:"SplitToningHighlightHue"`
	SplitToningHighlightSaturation                     int      `json:"SplitToningHighlightSaturation"`
	SplitToningShadowHue                               int      `json:"SplitToningShadowHue"`
	SplitToningShadowSaturation                        int      `json:"SplitToningShadowSaturation"`
	SubSecCreateDate                                   string   `json:"SubSecCreateDate"`
	SubSecDateTimeOriginal                             string   `json:"SubSecDateTimeOriginal"`
	SubSecModifyDate                                   string   `json:"SubSecModifyDate"`
	SubSecTime                                         int      `json:"SubSecTime"`
	SubSecTimeDigitized                                int      `json:"SubSecTimeDigitized"`
	SubSecTimeOriginal                                 int      `json:"SubSecTimeOriginal"`
	SubjectArea                                        string   `json:"SubjectArea"`
	SubjectDistanceRange                               int      `json:"SubjectDistanceRange"`
	SubjectSwitching                                   int      `json:"SubjectSwitching"`
	SubjectToDetect                                    int      `json:"SubjectToDetect"`
	TargetAperture                                     float64  `json:"TargetAperture"`
	TargetExposureTime                                 float64  `json:"TargetExposureTime"`
	Technology                                         string   `json:"Technology"`
	ThumbnailImage                                     string   `json:"ThumbnailImage"`
	ThumbnailImageValidArea                            string   `json:"ThumbnailImageValidArea"`
	ThumbnailLength                                    int      `json:"ThumbnailLength"`
	ThumbnailOffset                                    int      `json:"ThumbnailOffset"`
	TimeCreated                                        string   `json:"TimeCreated"`
	TimeZone                                           int      `json:"TimeZone"`
	TimeZoneCity                                       int      `json:"TimeZoneCity"`
	Tint                                               string   `json:"Tint"`
	ToneCurve                                          int      `json:"ToneCurve"`
	ToneCurveBlue                                      []string `json:"ToneCurveBlue"`
	ToneCurveGreen                                     []string `json:"ToneCurveGreen"`
	ToneCurveName                                      string   `json:"ToneCurveName"`
	ToneCurveName2012                                  string   `json:"ToneCurveName2012"`
	ToneCurvePV2012                                    []string `json:"ToneCurvePV2012"`
	ToneCurvePV2012Blue                                []string `json:"ToneCurvePV2012Blue"`
	ToneCurvePV2012Green                               []string `json:"ToneCurvePV2012Green"`
	ToneCurvePV2012Red                                 []string `json:"ToneCurvePV2012Red"`
	ToneCurveRed                                       []string `json:"ToneCurveRed"`
	ToneMapStrength                                    int      `json:"ToneMapStrength"`
	ToyCameraFilter                                    int      `json:"ToyCameraFilter"`
	USMLensElectronicMF                                int      `json:"USMLensElectronicMF"`
	UnsharpMaskFineness                                int      `json:"UnsharpMaskFineness"`
	UnsharpMaskThreshold                               int      `json:"UnsharpMaskThreshold"`
	UprightCenterMode                                  int      `json:"UprightCenterMode"`
	UprightCenterNormX                                 float64  `json:"UprightCenterNormX"`
	UprightCenterNormY                                 float64  `json:"UprightCenterNormY"`
	UprightFocalLength35Mm                             int      `json:"UprightFocalLength35mm"`
	UprightFocalMode                                   int      `json:"UprightFocalMode"`
	UprightFourSegmentsCount                           int      `json:"UprightFourSegmentsCount"`
	UprightPreview                                     bool     `json:"UprightPreview"`
	UprightTransformCount                              int      `json:"UprightTransformCount"`
	UprightVersion                                     int      `json:"UprightVersion"`
	UsePanoramaViewer                                  bool     `json:"UsePanoramaViewer"`
	UserComment                                        string   `json:"UserComment"`
	VFDisplayIllumination                              int      `json:"VFDisplayIllumination"`
	VRDOffset                                          int      `json:"VRDOffset"`
	ValidAFPoints                                      int      `json:"ValidAFPoints"`
	Version                                            float64  `json:"Version"`
	Vibrance                                           string   `json:"Vibrance"`
	ViewingCondDesc                                    string   `json:"ViewingCondDesc"`
	ViewingCondIlluminant                              string   `json:"ViewingCondIlluminant"`
	ViewingCondIlluminantType                          int      `json:"ViewingCondIlluminantType"`
	ViewingCondSurround                                string   `json:"ViewingCondSurround"`
	VignetteAmount                                     int      `json:"VignetteAmount"`
	VignetteCorrectionAlreadyApplied                   bool     `json:"VignetteCorrectionAlreadyApplied"`
	VignettingCorrVersion                              int      `json:"VignettingCorrVersion"`
	WBBracketMode                                      int      `json:"WBBracketMode"`
	WBBracketValueAB                                   int      `json:"WBBracketValueAB"`
	WBBracketValueGM                                   int      `json:"WBBracketValueGM"`
	WBShiftAB                                          int      `json:"WBShiftAB"`
	WBShiftGM                                          int      `json:"WBShiftGM"`
	WBRGGBLevels                                       string   `json:"WB_RGGBLevels"`
	WBRGGBLevelsAsShot                                 string   `json:"WB_RGGBLevelsAsShot"`
	WBRGGBLevelsAuto                                   string   `json:"WB_RGGBLevelsAuto"`
	WBRGGBLevelsCloudy                                 string   `json:"WB_RGGBLevelsCloudy"`
	WBRGGBLevelsDaylight                               string   `json:"WB_RGGBLevelsDaylight"`
	WBRGGBLevelsFlash                                  string   `json:"WB_RGGBLevelsFlash"`
	WBRGGBLevelsFluorescent                            string   `json:"WB_RGGBLevelsFluorescent"`
	WBRGGBLevelsKelvin                                 string   `json:"WB_RGGBLevelsKelvin"`
	WBRGGBLevelsMeasured                               string   `json:"WB_RGGBLevelsMeasured"`
	WBRGGBLevelsShade                                  string   `json:"WB_RGGBLevelsShade"`
	WBRGGBLevelsTungsten                               string   `json:"WB_RGGBLevelsTungsten"`
	WatercolorFilter                                   int      `json:"WatercolorFilter"`
	WhiteBalance                                       int      `json:"WhiteBalance"`
	WhiteBalanceBlue                                   int      `json:"WhiteBalanceBlue"`
	WhiteBalanceRed                                    int      `json:"WhiteBalanceRed"`
	Whites2012                                         string   `json:"Whites2012"`
	WholeAreaTracking                                  int      `json:"WholeAreaTracking"`
	XMPToolkit                                         string   `json:"XMPToolkit"`
	XResolution                                        int      `json:"XResolution"`
	YCbCrPositioning                                   int      `json:"YCbCrPositioning"`
	YCbCrSubSampling                                   string   `json:"YCbCrSubSampling"`
	YResolution                                        int      `json:"YResolution"`
	ZoomSourceWidth                                    int      `json:"ZoomSourceWidth"`
	ZoomTargetWidth                                    int      `json:"ZoomTargetWidth"`
}

func (Jpeg) MediaType() string { return MediaTypeImage }

func (j Jpeg) ToCommon() CommonMetadata {
	return CommonMetadata{
		ExifToolVersion:      ftoa(j.ExifToolVersion),
		SourceFile:           j.SourceFile,
		Directory:            j.Directory,
		FileName:             j.FileName,
		FileSize:             itoa(j.FileSize),
		FilePermissions:      itoa(j.FilePermissions),
		FileType:             j.FileType,
		FileTypeExtension:    j.FileTypeExtension,
		MIMEType:             j.MIMEType,
		FileModifyDate:       j.FileModifyDate,
		FileAccessDate:       j.FileAccessDate,
		FileInodeChangeDate:  j.FileInodeChangeDate,
		ImageWidth:           itoa(j.ImageWidth),
		ImageHeight:          itoa(j.ImageHeight),
		ImageSize:            j.ImageSize,
		Megapixels:           ftoa(j.Megapixels),
		Orientation:          itoa(j.Orientation),
		Make:                 j.Make,
		Model:                j.Model,
		LensModel:            j.LensModel,
		Software:             ftoa(j.Software),
		CreateDate:           j.CreateDate,
		ModifyDate:           j.ModifyDate,
		DateTimeOriginal:     j.DateTimeOriginal,
		ISO:                  itoa(j.Iso),
		Aperture:             ftoa(j.Aperture),
		FNumber:              ftoa(j.FNumber),
		FocalLength:          ftoa(j.FocalLength),
		ExposureTime:         ftoa(j.ExposureTime),
		ShutterSpeed:         ftoa(j.ShutterSpeed),
		ExposureMode:         itoa(j.ExposureMode),
		ExposureProgram:      itoa(j.ExposureProgram),
		ExposureCompensation: itoa(j.ExposureCompensation),
		Flash:                itoa(j.Flash),
		MeteringMode:         itoa(j.MeteringMode),
		WhiteBalance:         itoa(j.WhiteBalance),
		GPSLatitude:          ftoa(j.GPSLatitude),
		GPSLongitude:         ftoa(j.GPSLongitude),
		GPSAltitude:          ftoa(j.GPSAltitude),
		GPSAltitudeRef:       itoa(j.GPSAltitudeRef),
		GPSPosition:          j.GPSPosition,
	}
}
