// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/internal/v1/admin/reset": {
            "post": {
                "description": "Deletes all scan sessions, file registry entries, content groups and group members in a single transaction. Irreversible.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Reset all application data",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/admin.ResetResponse"
                        }
                    }
                }
            }
        },
        "/internal/v1/hash/progress": {
            "get": {
                "description": "Returns files_discovered, files_hashed, files_errored and percent_complete for the given session.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Hash"
                ],
                "summary": "Get hashing progress for a scan session",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Scan session UUID",
                        "name": "session_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/hash.HashProgressResponse"
                        }
                    }
                }
            }
        },
        "/internal/v1/hash/stats": {
            "get": {
                "description": "Returns aggregate counts across all content groups: total groups, duplicates, masters elected.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Hash"
                ],
                "summary": "Get overall content group statistics",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/hash.HashStatsResponse"
                        }
                    }
                }
            }
        },
        "/internal/v1/scans/cleanup-output": {
            "post": {
                "description": "Checks every ORGANIZED entry in the file registry and removes those whose\nfiles no longer exist on disk. Does NOT re-index or re-sort any files.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Scans"
                ],
                "summary": "Clean up stale organized-library entries",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/scans.CleanupOutputResponse"
                        }
                    }
                }
            }
        },
        "/internal/v1/scans/count": {
            "get": {
                "description": "Get the total number of files scanned across all sessions",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Scans"
                ],
                "summary": "Get total file count",
                "responses": {
                    "200": {
                        "description": "Total file count",
                        "schema": {
                            "$ref": "#/definitions/scans.FileCountResponse"
                        }
                    }
                }
            }
        },
        "/internal/v1/scans/start": {
            "post": {
                "description": "Start a new scan session with specified root paths",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Scans"
                ],
                "summary": "Start a new scan session",
                "parameters": [
                    {
                        "description": "Start Scan Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/scans.StartScanRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/scans.StartScanResponse"
                        }
                    }
                }
            }
        },
        "/internal/v1/scans/status": {
            "get": {
                "description": "Get the status of a scan session",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Scans"
                ],
                "summary": "Get scan status",
                "parameters": [
                    {
                        "type": "string",
                        "name": "sessionId",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/scanner.ScanSession"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "admin.ResetResponse": {
            "type": "object",
            "properties": {
                "contentGroupsDeleted": {
                    "type": "integer"
                },
                "filesDeleted": {
                    "type": "integer"
                },
                "groupMembersDeleted": {
                    "type": "integer"
                },
                "scanSessionsDeleted": {
                    "type": "integer"
                }
            }
        },
        "hash.HashProgressResponse": {
            "type": "object",
            "properties": {
                "completedAt": {
                    "type": "string"
                },
                "filesDiscovered": {
                    "type": "integer"
                },
                "filesErrored": {
                    "type": "integer"
                },
                "filesHashed": {
                    "type": "integer"
                },
                "percentComplete": {
                    "type": "number"
                },
                "sessionId": {
                    "type": "string"
                },
                "startedAt": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "hash.HashStatsResponse": {
            "type": "object",
            "properties": {
                "duplicateFiles": {
                    "type": "integer"
                },
                "groupsWithDupes": {
                    "type": "integer"
                },
                "mastersElected": {
                    "type": "integer"
                },
                "totalFiles": {
                    "type": "integer"
                },
                "totalGroups": {
                    "type": "integer"
                }
            }
        },
        "scanner.ScanSession": {
            "type": "object",
            "properties": {
                "completedAt": {
                    "type": "string"
                },
                "errorsEncountered": {
                    "type": "integer"
                },
                "filesDiscovered": {
                    "type": "integer"
                },
                "filesModified": {
                    "type": "integer"
                },
                "filesNew": {
                    "type": "integer"
                },
                "filesSkipped": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "lastError": {
                    "type": "string"
                },
                "rootPaths": {
                    "description": "JSONB in DB",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "startedAt": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "scans.CleanupOutputResponse": {
            "type": "object",
            "properties": {
                "deletedCount": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "scans.FileCountResponse": {
            "type": "object",
            "properties": {
                "totalFiles": {
                    "type": "integer"
                }
            }
        },
        "scans.StartScanRequest": {
            "type": "object",
            "required": [
                "rootPaths"
            ],
            "properties": {
                "rootPaths": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "scans.StartScanResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "sessionId": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "WanderSort API",
	Description:      "API documentation for WanderSort",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
