// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/internal/v1/admin/reset": {
            "post": {
                "description": "Deletes all scan sessions, file registry entries, content groups and group members in a single transaction. Irreversible.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Reset all application data",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/admin.ResetResponse"
                        }
                    }
                }
            }
        },
        "/internal/v1/pipeline/count": {
            "get": {
                "description": "Returns the number of files discovered by the scanner and the number hashed.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Pipeline"
                ],
                "summary": "Get combined file counts",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pipeline.FileCountResponse"
                        }
                    }
                }
            }
        },
        "/internal/v1/pipeline/start": {
            "post": {
                "description": "Submit root paths to the pipeline. Scanning and hashing run automatically.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Pipeline"
                ],
                "summary": "Start a new pipeline scan",
                "parameters": [
                    {
                        "description": "Start Scan Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/pipeline.StartScanRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/pipeline.StartScanResponse"
                        }
                    }
                }
            }
        },
        "/internal/v1/pipeline/ws": {
            "get": {
                "description": "Opens a WebSocket connection that pushes PipelineStatus JSON messages in real time.",
                "tags": [
                    "Pipeline"
                ],
                "summary": "Stream pipeline status via WebSocket",
                "responses": {
                    "101": {
                        "description": "Switching Protocols",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "admin.ResetResponse": {
            "type": "object",
            "properties": {
                "contentGroupsDeleted": {
                    "type": "integer"
                },
                "filesDeleted": {
                    "type": "integer"
                },
                "groupMembersDeleted": {
                    "type": "integer"
                },
                "scanSessionsDeleted": {
                    "type": "integer"
                }
            }
        },
        "pipeline.FileCountResponse": {
            "type": "object",
            "properties": {
                "filesHashed": {
                    "type": "integer"
                },
                "filesScanned": {
                    "type": "integer"
                }
            }
        },
        "pipeline.StartScanRequest": {
            "type": "object",
            "required": [
                "rootPaths"
            ],
            "properties": {
                "rootPaths": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "pipeline.StartScanResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "sessionId": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "WanderSort API",
	Description:      "API documentation for WanderSort",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
